# TCL File Generated by Component Editor 16.1
# Tue Mar 28 02:46:40 PDT 2017
# DO NOT MODIFY


# 
# vga_fb "vga frame buff" v1.0
# Peter LI 2017.03.28.02:46:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_fb
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_fb
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Peter Li"
set_module_property DISPLAY_NAME "vga frame buff"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 

